analyze_codebase_task:
  description: >
    """
    Generate summary report with:
    1. List of files that need to be modified for Auth0 integration
    2. For each file:
       - Current purpose/role of the file
       - Required Auth0-related changes
       - Description of the edits needed
       - Any dependencies or prerequisites for the changes
    3. Framework-specific considerations
    4. Comments for downstream agents

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "files_to_modify": [
        {
          "file_path": "string",
          "current_purpose": "string",
          "required_changes": ["string"],
          "dependencies": ["string"],
          "framework_notes": "string"
        }
      ],
      "framework_considerations": {
        "framework_type": "string",
        "auth_patterns": ["string"],
        "security_requirements": ["string"]
      }
    }

analyze_requirements_task:
  description: >
    """
    Read and analyze the auth0_integration.md file to extract and structure key information in the file then generate a concise, actionable report for downstream agents.
    Focus on:
    1. Application type and authentication methods
    2. URL configurations and redirects
    3. User experience requirements
    4. Security settings and policies
    5. Role-based access control needs
    6. API requirements
    7. Custom data and migration needs

    Final answer MUST be a structured JSON report containing:
    - application_type: Type of application and authentication methods
    - url_configurations: All required URLs and redirects
    - user_experience: Login/logout flows and UI requirements
    - security_settings: MFA and password policies
    - access_control: RBAC configuration if needed
    - api_requirements: API security needs
    - custom_data: Custom claims and user metadata requirements
    - migration_needs: Any existing user migration requirements

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "application_type": {
        "type": "string",
        "authentication_methods": ["string"]
      },
      "url_configurations": {
        "callback_urls": ["string"],
        "logout_urls": ["string"],
        "web_origins": ["string"],
        "cors_origins": ["string"]
      },
      "user_experience": {
        "login_redirect": "string",
        "logout_redirect": "string",
        "custom_login_page": "boolean",
        "branding": {
          "background_color": "string",
          "logo_url": "string"
        }
      },
      "security_settings": {
        "mfa": {
          "enabled": "boolean",
          "type": "string"
        },
        "password_policy": {
          "min_length": "number",
          "complexity": "string"
        }
      },
      "access_control": {
        "rbac_enabled": "boolean",
        "roles": ["string"],
        "permissions": ["string"]
      },
      "api_requirements": {
        "api_secured": "boolean",
        "audience": "string",
        "scopes": ["string"]
      },
      "custom_data": {
        "custom_claims": {
          "enabled": "boolean",
          "claims": ["string"]
        },
        "user_metadata": {
          "enabled": "boolean",
          "fields": ["string"]
        }
      },
      "migration_needs": {
        "required": "boolean",
        "source": "string"
      }
    }

integrate_auth0_task:
  description: >
    """
    Update all code to implement Auth0 integration based on analysis report and Codebase Analysis Agent. Use validation agent to ensure the integration is correct, if issues are found, fix it.
    Focus on:
    1. Generating secure, framework-specific Auth0 code
    2. Injecting code into appropriate files
    3. Ensuring proper error handling
    4. Following Auth0 best practices
    5. Maintaining code readability and maintainability

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "modified_files": [
        {
          "file_path": "string",
          "changes_made": ["string"],
          "status": "string"
        }
      ],
      "integration_summary": {
        "success": "boolean",
        "issues": ["string"],
        "recommendations": ["string"]
      }
    }

validate_integration_task:
  description: >
    """
    Analyze Auth0 integration for common security pitfalls:
    1. Hardcoded credentials in code
    2. Missing CSRF protection
    3. Improper token storage/handling
    4. Insecure session management
    5. Missing error handling
    6. Incorrect callback URL validation
    7. Insufficient logging
    8. Missing rate limiting
    9. Insecure password policies
    10. Improper role/permission checks

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "validation_results": {
        "overall_status": "string",
        "confidence_score": "number",
        "issues_found": [
          {
            "type": "string",
            "severity": "string",
            "description": "string",
            "recommendation": "string"
          }
        ],
        "security_checks": [
          {
            "check": "string",
            "status": "string",
            "details": "string"
          }
        ]
      }
    }

