analyze_codebase_task:
  description: >
    """
    Analyze the codebase to identify files that need Auth0 integration. Only keep files that are relevant to Auth0 integration.
    For each file:
    1. Determine its current purpose and role
    2. List required Auth0-related changes
    3. Identify dependencies and prerequisites
    4. Consider framework-specific requirements

    Final answer MUST be a structured JSON report containing:
    - files_to_modify: List of files needing changes
    - framework_considerations: Framework-specific requirements
    - dependencies: Project-wide dependencies

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "files_to_modify": [
        {
          "file_path": "string",
          "current_purpose": "string",
          "required_changes": ["string"],
          "dependencies": ["string"],
          "framework_notes": "string"
        }
      ],
      "framework_considerations": {
        "framework_type": "string",
        "auth_patterns": ["string"],
        "security_requirements": ["string"]
      },
      "dependencies": {
        "required_packages": ["string"],
        "environment_variables": ["string"],
        "configuration_files": ["string"]
      }
    }

analyze_requirements_task:
  description: >
    """
    Analyze the project's dependencies and requirements for Auth0 integration.
    For each dependency:
    1. Check version compatibility with Auth0 requirements
    2. Identify any missing dependencies
    3. Validate security requirements
    4. Ensure all necessary packages are listed

    Final answer MUST be a structured JSON report containing:
    - current_dependencies: List of current project dependencies
    - required_dependencies: List of dependencies needed for Auth0
    - version_compatibility: Compatibility analysis
    - security_requirements: Security-related package requirements
    - missing_dependencies: List of missing required packages

    PROJECT PATH:
    ----------
    {project_path}
    """
  expected_output: >
    {
      "current_dependencies": [
        {
          "package": "string",
          "version": "string",
          "purpose": "string"
        }
      ],
      "required_dependencies": [
        {
          "package": "string",
          "version": "string",
          "purpose": "string",
          "is_installed": "boolean"
        }
      ],
      "version_compatibility": {
        "compatible_packages": ["string"],
        "incompatible_packages": [
          {
            "package": "string",
            "current_version": "string",
            "required_version": "string",
            "reason": "string"
          }
        ]
      },
      "security_requirements": [
        {
          "requirement": "string",
          "status": "string",
          "package": "string"
        }
      ],
      "missing_dependencies": [
        {
          "package": "string",
          "version": "string",
          "purpose": "string"
        }
      ]
    }

